fix: Globs not working on Windows.
sanity-io/pkg-utils pull request #85
Opened 2023-03-18 13:44 UTC by vitorrd

Fixes #84 and [related @sanity/plugin-kit issue](https://github.com/sanity-io/plugin-kit/issues/61).

2023-03-19 11:52 UTC, snorrees approved these changes

2023-03-19 11:53 UTC, snorrees requested changes
There are li

2023-03-19 11:53 UTC, snorrees commented on src/node/globFiles.ts
> +import path from 'path'
Lint errors need to be fixed.

2023-03-20 14:03 UTC, stipsan approved these changes

2023-03-20 14:08 UTC, merged

2023-03-20 14:09 UTC, stipsan commented
There were a couple of failing windows tests, fixing them in another commit and merging for now. Need to bootup my windows box 🧑‍💻